baseURL = ''
languageCode = 'en-us'
title = 'My New Hugo Site'
sectionPagesMenu = 'main'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
[params]
  math = true

[taxonomies]
  tag = 'tags'